tasks:
  - tox -e py27
  - tox -e py34
  - flake8
  - isort -c -rc frigg_runner tests
  - coverage combine && coverage xml && coverage report

verbose_tasks:
  - coverage combine && coverage xml && coverage report

comment: false

coverage:
  path: coverage.xml
  parser: python
