tasks:
  - tox -e py27-tests
  - tox -e py34-tests
  - tox -e py35-tests
  - tox -e flake8
  - tox -e isort
  - tox -e coverage

verbose_tasks:
  - tox -e coverage

coverage:
  path: coverage.xml
  parser: python
