tasks:
  - tox -e flake8
  - tox -e isort
  - tox -e py27-tests
  - tox -e py34-tests
  - coverage xml && coverage report

verbose_tasks:
  - coverage xml && coverage report

coverage:
  path: coverage.xml
  parser: python
